/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/body/Navbar";
import Body from "@/components/body/Body";
import Footer from "@/components/body/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Little Teti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="use-credentials"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Body />
        <Footer /> 
      </main>
    </>
  );
}
