export let cores = [
    { cor: "Água", hex: "#00FFFF" },
    { cor: "Azul turquesa", hex: "#00CCEE" },
    { cor: "Azul turquesa brilhante", hex: "#00DDFF" },
    { cor: "Azul brasilis", hex: "#00BDCE" },
    { cor: "Azul brasilis brilhante", hex: "#09ACDB" },
    { cor: "Azul Tóquio", hex: "#1981CD" },
    { cor: "Água-marinha", hex: "#7FFFD4" },
    { cor: "Água-marinha média", hex: "#66CDAA" },
    { cor: "Azul celeste", hex: "#00A4CD" },
    { cor: "Alizarina", hex: "#E32636" },
    { cor: "Amarelo", hex: "#FFFF00" },
    { cor: "Amarelo brasilis", hex: "#ECDB00" },
    { cor: "Amarelo creme", hex: "#ECD690" },
    { cor: "Amarelo claro", hex: "#FFFFE0" },
    { cor: "Amarelo escuro", hex: "#F2B73F" },
    { cor: "Amarelo esverdeado", hex: "#ADFF2F" },
    { cor: "Amarelo ouro claro", hex: "#FAFAD2" },
    { cor: "Amarelo queimado", hex: "#EEAD2D" },
    { cor: "Âmbar", hex: "#FFBF00" },
    { cor: "Ameixa", hex: "#DDA0DD" },
    { cor: "Ametista", hex: "#9966CC" },
    { cor: "Amêndoa", hex: "#FFEBCD" },
    { cor: "Aspargo", hex: "#7BA05B" },
    { cor: "Azul", hex: "#0000FF" },
    { cor: "Azul alice", hex: "#F0F8FF" },
    { cor: "Azul ardósia", hex: "#6A5ACD" },
    { cor: "Azul ardósia claro", hex: "#8470FF" },
    { cor: "Azul ardósia escuro", hex: "#483D8B" },
    { cor: "Azul ardósia médio", hex: "#7B68EE" },
    { cor: "Azul areado", hex: "#B8CAD4" },
    { cor: "Azul aço", hex: "#4682B4" },
    { cor: "Azul aço claro", hex: "#B0C4DE" },
    { cor: "Azul cadete", hex: "#5F9EA0" },
    { cor: "Azul camarada", hex: "#054F77" },
    { cor: "Azul celeste", hex: "#F0FFFF" },
    { cor: "Azul celeste brilhante", hex: "#007FFF" },
    { cor: "Azul claro", hex: "#ADD8E6" },
    { cor: "Azul cobalto", hex: "#0047AB" },
    { cor: "Azul céu", hex: "#87CEEB" },
    { cor: "Azul céu claro", hex: "#87CEFA" },
    { cor: "Azul céu profundo", hex: "#00BFFF" },
    { cor: "Azul escuro", hex: "#00008B" },
    { cor: "Azul flor de milho", hex: "#6495ED" },
    { cor: "Azul força aérea", hex: "#5D8AA8" },
    { cor: "Azul furtivo", hex: "#1E90FF" },
    { cor: "Azul manteiga", hex: "#a6aa3e" },
    { cor: "Azul marinho", hex: "#120A8F" },
    { cor: "Azul meia-noite", hex: "#191970" },
    { cor: "Azul médio", hex: "#0000CD" },
    { cor: "Azul petróleo", hex: "#084D6E" },
    { cor: "Azul pólvora", hex: "#B0E0E6" },
    { cor: "Azul taparuere", hex: "#248EFF" },
    { cor: "Azul real", hex: "#0000DD" },
    { cor: "Azul violeta", hex: "#8A2BE2" },
    { cor: "Açafrão", hex: "#F4C430" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Bege", hex: "#F5F5DC" },
    { cor: "Bordô", hex: "#800000" },
    { cor: "Borgonha", hex: "#900020" },
    { cor: "Branco", hex: "#FFFFFF" },
    { cor: "Branco antigo", hex: "#FAEBD7" },
    { cor: "Branco fantasma", hex: "#F8F8FF" },
    { cor: "Branco floral", hex: "#FFFAF0" },
    { cor: "Branco fumaça", hex: "#F5F5F5" },
    { cor: "Branco navajo", hex: "#FFDEAD" },
    { cor: "Brasil", hex: "#A7F432" },
    { cor: "Bronze", hex: "#CD7F32" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Caramelo", hex: "#8B5742" },
    { cor: "Caqui", hex: "#F0E68C" },
    { cor: "Cardo", hex: "#D8BFD8" },
    { cor: "Carmesim", hex: "#DC143C" },
    { cor: "Carmim", hex: "#712F26" },
    { cor: "Carmim clássico", hex: "#992244" },
    { cor: "Carmim carnáceo", hex: "#960018" },
    { cor: "Castanho avermelhado", hex: "#8B0000" },
    { cor: "Castanho claro", hex: "#D2B48C" },
    { cor: "Cenoura", hex: "#ED9121" },
    { cor: "Cereja", hex: "#DE3163" },
    { cor: "Cereja Hollywood", hex: "#F400A1" },
    { cor: "Chocolate", hex: "#D2691E" },
    { cor: "Ciano", hex: "#00FFFF" },
    { cor: "Ciano claro", hex: "#E0FFFF" },
    { cor: "Ciano escuro", hex: "#008B8B" },
    { cor: "Cinza", hex: "#808080" },
    { cor: "Cinza ardósia", hex: "#708090" },
    { cor: "Cinza ardósia claro", hex: "#778899" },
    { cor: "Cinza ardósia escuro", hex: "#2F4F4F" },
    { cor: "Cinza claro", hex: "#D3D3D3" },
    { cor: "Cinza escuro", hex: "#A9A9A9" },
    { cor: "Cinza fosco", hex: "#696969" },
    { cor: "Cinza médio", hex: "#DCDCDC" },
    { cor: "Cobre", hex: "#B87333" },
    { cor: "Concha", hex: "#FFF5EE" },
    { cor: "Coral", hex: "#FF7F50" },
    { cor: "Coral claro", hex: "#F08080" },
    { cor: "Couro", hex: "#F0DC82" },
    { cor: "Creme", hex: "#FFFDD0" },
    { cor: "Creme de marisco", hex: "#FFE4C4" },
    { cor: "Creme de menta", hex: "#F5FFFA" },
    { cor: "Caqui escuro", hex: "#BDB76B" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Dainise", hex: "#778899" },
    { cor: "Dourado", hex: "#DAA520" },
    { cor: "Dourado escuro", hex: "#B8860B" },
    { cor: "Dourado pálido", hex: "#EEE8AA" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Ébano", hex: "#555D50" },
    { cor: "Eminência", hex: "#6C3082" },
    { cor: "Escarlate", hex: "#FF2400" },
    { cor: "Esmeralda", hex: "#50C878" },
    { cor: "Eucalipto", hex: "#44D7A8" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Fandango", hex: "#B53389" },
    { cor: "Feldspato", hex: "#FDD5B1" },
    { cor: "Ferrugem", hex: "#B7410E" },
    { cor: "Flerte", hex: "#A2006D" },
    { cor: "Fuligem", hex: "#3D2B1F" },
    { cor: "Fúchsia", hex: "#FF00FF" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Grená", hex: "#831D1C" },
    { cor: "Gainsboro", hex: "#DCDCDC" },
    { cor: "Glitter", hex: "#E6E8FA" },
    { cor: "Goiaba", hex: "#Be5b59" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Herbal", hex: "#2E8B57" },
    { cor: "Heliotrópio", hex: "#DF73FF" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Índigo", hex: "#4B0082" },
    { cor: "Independência", hex: "#4C516D" },
    { cor: "Iris", hex: "#5A4FCF" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Jade", hex: "#00A86B" },
    { cor: "Jambo", hex: "#FF4500" },
    { cor: "Jasmine", hex: "#F8DE7E" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Kiwi", hex: "#8EE53F" },
    { cor: "Kobi", hex: "#E79FC4" },
    { cor: "Kobicha", hex: "#6B4423" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Laranja", hex: "#FFA500" },
    { cor: "Laranja escuro", hex: "#FF8C00" },
    { cor: "Laranja claro", hex: "#FFB84D" },
    { cor: "Lavanda", hex: "#E6E6FA" },
    { cor: "Lavanda avermelhada", hex: "#FFF0F5" },
    { cor: "Lilás", hex: "#C8A2C8" },
    { cor: "Lima", hex: "#00FF00" },
    { cor: "Lemon", hex: "#FDE910" },
    { cor: "Linho", hex: "#FAF0E6" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Madeira", hex: "#DEB887" },
    { cor: "Magenta", hex: "#FF00FF" },
    { cor: "Magenta escuro", hex: "#8B008B" },
    { cor: "Malva", hex: "#E0B0FF" },
    { cor: "Mamão batido", hex: "#FFEFD5" },
    { cor: "Maná", hex: "#F0FFF0" },
    { cor: "Marfim", hex: "#FFFFF0" },
    { cor: "Marrom", hex: "#964b00" },
    { cor: "Marrom amarelado", hex: "#F4A460" },
    { cor: "Marrom claro", hex: "#A52A2A" },
    { cor: "Marrom rosado", hex: "#BC8F8F" },
    { cor: "Marrom sela", hex: "#8B4513" },
    { cor: "Milho", hex: "#FBEC5D" },
    { cor: "Milho Claro", hex: "#FFF8DC" },
    { cor: "Mocassim", hex: "#FFE4B5" },
    { cor: "Mostarda", hex: "#FFDB58" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Naval", hex: "#000080" },
    { cor: "Neve", hex: "#FFFAFA" },
    { cor: "Nyanza", hex: "#E9FFDB" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Ocre", hex: "#CC7722" },
    { cor: "Oliva", hex: "#808000" },
    { cor: "Oliva escura", hex: "#556B2F" },
    { cor: "Oliva parda", hex: "#6B8E23" },
    { cor: "Orquídea", hex: "#DA70D6" },
    { cor: "Orquídea escura", hex: "#9932CC" },
    { cor: "Orquídea média", hex: "#BA55D3" },
    { cor: "Ouro", hex: "#FFD700" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Pardo", hex: "#CD853F" },
    { cor: "Pardo escuro", hex: "#CC6600" },
    { cor: "Prata", hex: "#C0C0C0" },
    { cor: "Preto", hex: "#000000" },
    { cor: "Pêssego", hex: "#FFDAB9" },
    { cor: "Púrpura", hex: "#800080" },
    { cor: "Púrpura média", hex: "#9370DB" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Quantum", hex: "#111111" },
    { cor: "Quartz", hex: "#51484F" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Renda antiga", hex: "#FDF5E6" },
    { cor: "Rosa", hex: "#FFCBDB" },
    { cor: "Rosa brilhante", hex: "#FF007F" },
    { cor: "Rosa Choque", hex: "#FC0FC0" },
    { cor: "Rosa amoroso", hex: "#CD69CD" },
    { cor: "Rosa claro", hex: "#FFB6C1" },
    { cor: "Rosa danação", hex: "#DA69A1" },
    { cor: "Rosa embaçado", hex: "#FFE4E1" },
    { cor: "Rosa forte", hex: "#FF69B4" },
    { cor: "Rosa profundo", hex: "#FF1493" },
    { cor: "Roxo", hex: "#993399" },
    { cor: "Roxo brasilis", hex: "#8A008A" },
    { cor: "Rútilo", hex: "#6D351A" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Salmão", hex: "#FA7F72" },
    { cor: "Salmão claro", hex: "#FFA07A" },
    { cor: "Salmão escuro", hex: "#E9967A" },
    { cor: "Siena", hex: "#FF8247" },
    { cor: "Sépia", hex: "#705714" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Tangerina", hex: "#F28500" },
    { cor: "Terracota", hex: "#E2725B" },
    { cor: "Tijolo refratário", hex: "#B22222" },
    { cor: "Tomate", hex: "#FF6347" },
    { cor: "Trigo", hex: "#F5DEB3" },
    { cor: "Triássico", hex: "#FF2401" },
    { cor: "Turquesa", hex: "#40E0D0" },
    { cor: "Turquesa escura", hex: "#00CED1" },
    { cor: "Turquesa média", hex: "#48D1CC" },
    { cor: "Turquesa pálida", hex: "#AFEEEE" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Ube", hex: "#8878C3" },
    { cor: "Urucum", hex: "#EC2300" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Verde", hex: "#008000" },
    { cor: "Verde espectro", hex: "#00FF00" },
    { cor: "Verde amarelado", hex: "#9ACD32" },
    { cor: "Verde claro", hex: "#90EE90" },
    { cor: "Verde escuro", hex: "#006400" },
    { cor: "Verde floresta", hex: "#228B22" },
    { cor: "Verde fluorescente", hex: "#CCFF33" },
    { cor: "Verde lima", hex: "#32CD32" },
    { cor: "Verde grama", hex: "#7CFC00" },
    { cor: "Verde mar claro", hex: "#20B2AA" },
    { cor: "Verde mar escuro", hex: "#8FBC8F" },
    { cor: "Verde mar médio", hex: "#3CB371" },
    { cor: "Verde militar", hex: "#78866B" },
    { cor: "Verde-oliva", hex: "#6B8E23" },
    { cor: "Verde Paris", hex: "#7FFF00" },
    { cor: "Verde primavera", hex: "#00FF7F" },
    { cor: "Verde primavera médio", hex: "#00FA9A" },
    { cor: "Verde pálido", hex: "#98FB98" },
    { cor: "Verde-azulado", hex: "#008080" },
    { cor: "Vermelho", hex: "#FF0000" },
    { cor: "Vermelho enegrecido", hex: "#550000" },
    { cor: "Vermelho escuro", hex: "#8B0000" },
    { cor: "Vermelho indiano", hex: "#CD5C5C" },
    { cor: "Vermelho violeta", hex: "#D02090" },
    { cor: "Vermelho violeta médio", hex: "#C71585" },
    { cor: "Vermelho violeta pálido", hex: "#DB7093" },
    { cor: "Violeta", hex: "#EE82EE" },
    { cor: "Violeta escuro", hex: "#9400D3" },
    { cor: "Violeta claro", hex: "#F8CBF8" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Xanadu", hex: "#738678" },
    { cor: "Nome", hex: "Tripleto hex" },
    { cor: "Zaffre", hex: "#0014A8" }
  ];

